--[[
Spriteloq metadata
Generated by SpriteLoq: Loqheart's Flash SWF to sprite sheet Corona SDK exporter (c) Loqheart 2011
version 1.4.10
target Corona SDK
extension lua
exportName shape
exportPath file:///C:/Users/kirikoro/Desktop/animacino/Assets
sheetSize 2048x1024
sources 1
name; url; referencePoint; startFrame; totalFrames; frameRate; topLeft; bottomRight; sourceRect; loopParam; includeReverse; rasterize
Shape; ../Source/Shape.swf; (x=0, y=0); 1; 24; 30; (x=261, y=144); (x=613, y=409); (x=260, y=143, w=354, h=267); 1; false; false
assetShapes 0
]]

local sheet = false
local setInfo = false
local msFactor = 500  -- This should be 1000 ms. Corona BUG: The frame rate is playing back at around half speed at 30fps.

local function newSpriteSet(_sheet, _name, _startFrame, _frameCount, _frameRate, _loopParam, _xReference, _yReference, _spriteSourceWidth, _spriteSourceHeight, _unscaledSpriteX, _unscaledSpriteY, _unscaledSpriteWidth, _unscaledSpriteHeight, _frames, _shapeOnly)
    if (_shapeOnly) then
        return
    end

    local set = sprite.newSpriteSet(_sheet, _startFrame, _frameCount)
    sprite.add(set, _name, 1, _frameCount, (_frameCount / _frameRate) * msFactor, _loopParam)
    setInfo[_name] = {set = set, xReference = _xReference, yReference = _yReference, spriteSourceSize = {width = _spriteSourceWidth, height = _spriteSourceHeight}, unscaledSpriteRect = {x = _unscaledSpriteX, y = _unscaledSpriteY, width = _unscaledSpriteWidth, height = _unscaledSpriteHeight}, frames = _frames, frameRate = _frameRate, frameCount = _frameCount, fpss = _frameRate / 1000, startFrame = _startFrame}
end

local function load()
    local frameSets = {}
    local allFrames = {}

    frameSets["Shape"] = {
        {
            name="Shape-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=354, height=267},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=false,
        },
        {
            name="Shape-2",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=354, height=267},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=false,
        },
        {
            name="Shape-3",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=267, width=348, height=267},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-4",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=267, width=348, height=267},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-5",
            spriteColorRect={x=0, y=2},
            textureRect={x=343, y=534, width=354, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-6",
            spriteColorRect={x=0, y=2},
            textureRect={x=343, y=534, width=354, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-7",
            spriteColorRect={x=0, y=2},
            textureRect={x=697, y=532, width=343, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-8",
            spriteColorRect={x=0, y=2},
            textureRect={x=697, y=532, width=343, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-9",
            spriteColorRect={x=0, y=2},
            textureRect={x=706, y=0, width=326, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-10",
            spriteColorRect={x=0, y=2},
            textureRect={x=706, y=0, width=326, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-11",
            spriteColorRect={x=0, y=2},
            textureRect={x=348, y=267, width=354, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-12",
            spriteColorRect={x=0, y=2},
            textureRect={x=348, y=267, width=354, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-13",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=534, width=343, height=267},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-14",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=534, width=343, height=267},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-15",
            spriteColorRect={x=0, y=15},
            textureRect={x=1044, y=265, width=352, height=252},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-16",
            spriteColorRect={x=0, y=15},
            textureRect={x=1044, y=265, width=352, height=252},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-17",
            spriteColorRect={x=0, y=2},
            textureRect={x=354, y=0, width=352, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-18",
            spriteColorRect={x=0, y=2},
            textureRect={x=354, y=0, width=352, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-19",
            spriteColorRect={x=0, y=2},
            textureRect={x=702, y=265, width=342, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-20",
            spriteColorRect={x=0, y=2},
            textureRect={x=702, y=265, width=342, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-21",
            spriteColorRect={x=0, y=2},
            textureRect={x=1040, y=530, width=324, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-22",
            spriteColorRect={x=0, y=2},
            textureRect={x=1040, y=530, width=324, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-23",
            spriteColorRect={x=0, y=2},
            textureRect={x=1032, y=0, width=324, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        },
        {
            name="Shape-24",
            spriteColorRect={x=0, y=2},
            textureRect={x=1032, y=0, width=324, height=265},
            spriteSourceSize={width=354, height=267},
            spriteTrimmed=true,
        }
    }
    allFrames = table.copy(allFrames, frameSets["Shape"])


    sheet = sprite.newSpriteSheetFromData("shape.png", {frames = allFrames })

    -- setInfo table contains info about sprites: { (spriteName = {set: set, xReference: xReference, yReference: yReference, spriteSourceSize = {width: width, height: height}})+ }
    setInfo = {}
    newSpriteSet(sheet, "Shape", 1, 24, 30, 1, 0 - (354/2 + 260), 0 - (267/2 + 143), 354, 267, 0, 0, 354, 267, frameSets["Shape"], false)

    local shapes = {}
    shapes["Shape"] = {

    }

    return { sheet = sheet, setInfo = setInfo, shapes = shapes }
end

local function destroy()
    sheet:dispose()
    sheet = nil
    setInfo = nil
end

return { load = load, destroy = destroy }
